import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaNeon } from "@prisma/adapter-neon";

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const db = new PrismaClient({ adapter });

const customers = [
  { name: "Jane Cooper", company: "Microsoft", phone: "(225) 555-0118", email: "jane@microsoft.com", country: "United States", status: "Active" },
  { name: "Floyd Miles", company: "Yahoo", phone: "(205) 555-0100", email: "floyd@yahoo.com", country: "Kiribati", status: "Inactive" },
  { name: "Ronald Richards", company: "Adobe", phone: "(302) 555-0107", email: "ronald@adobe.com", country: "Israel", status: "Inactive" },
  { name: "Marvin McKinney", company: "Tesla", phone: "(252) 555-0126", email: "marvin@tesla.com", country: "Iran", status: "Active" },
  { name: "Jerome Bell", company: "Google", phone: "(629) 555-0129", email: "jerome@google.com", country: "Réunion", status: "Active" },
  { name: "Kathryn Murphy", company: "Microsoft", phone: "(406) 555-0120", email: "kathryn@microsoft.com", country: "Curaçao", status: "Active" },
  { name: "Jacob Jones", company: "Yahoo", phone: "(208) 555-0112", email: "jacob@yahoo.com", country: "Brazil", status: "Active" },
  { name: "Kristin Watson", company: "Facebook", phone: "(704) 555-0127", email: "kristin@facebook.com", country: "Åland Islands", status: "Inactive" },
  { name: "Cody Fisher", company: "Snapchat", phone: "(219) 555-0114", email: "cody@snapchat.com", country: "Palau", status: "Active" },
  { name: "Savannah Nguyen", company: "Twitter", phone: "(307) 555-0133", email: "savannah@twitter.com", country: "Canada", status: "Active" },
  { name: "Guy Hawkins", company: "Apple", phone: "(480) 555-0103", email: "guy@apple.com", country: "Germany", status: "Inactive" },
  { name: "Arlene McCoy", company: "Dropbox", phone: "(201) 555-0119", email: "arlene@dropbox.com", country: "France", status: "Active" },
  { name: "Devon Lane", company: "Spotify", phone: "(316) 555-0116", email: "devon@spotify.com", country: "Australia", status: "Active" },
  { name: "Ralph Edwards", company: "Netflix", phone: "(209) 555-0104", email: "ralph@netflix.com", country: "Japan", status: "Inactive" },
  { name: "Theresa Webb", company: "Amazon", phone: "(603) 555-0123", email: "theresa@amazon.com", country: "Nigeria", status: "Active" },
  { name: "Eleanor Pena", company: "Airbnb", phone: "(505) 555-0125", email: "eleanor@airbnb.com", country: "India", status: "Active" },
  { name: "Wade Warren", company: "Slack", phone: "(671) 555-0110", email: "wade@slack.com", country: "Mexico", status: "Inactive" },
  { name: "Courtney Henry", company: "Zoom", phone: "(302) 555-0108", email: "courtney@zoom.com", country: "United Kingdom", status: "Active" },
  { name: "Annette Black", company: "Shopify", phone: "(808) 555-0111", email: "annette@shopify.com", country: "Italy", status: "Active" },
  { name: "Cameron Williamson", company: "Stripe", phone: "(702) 555-0122", email: "cameron@stripe.com", country: "Spain", status: "Inactive" },
  { name: "Dianne Russell", company: "Salesforce", phone: "(907) 555-0101", email: "dianne@salesforce.com", country: "Brazil", status: "Active" },
  { name: "Brooklyn Simmons", company: "Oracle", phone: "(239) 555-0109", email: "brooklyn@oracle.com", country: "South Korea", status: "Active" },
  { name: "Albert Flores", company: "IBM", phone: "(414) 555-0118", email: "albert@ibm.com", country: "Sweden", status: "Inactive" },
  { name: "Darrell Steward", company: "SAP", phone: "(316) 555-0117", email: "darrell@sap.com", country: "Netherlands", status: "Active" },
  { name: "Leslie Alexander", company: "Nvidia", phone: "(316) 555-0190", email: "leslie@nvidia.com", country: "Singapore", status: "Active" },
  { name: "Jenny Wilson", company: "Intel", phone: "(270) 555-0117", email: "jenny@intel.com", country: "Taiwan", status: "Active" },
  { name: "Robert Fox", company: "AMD", phone: "(505) 555-0100", email: "robert@amd.com", country: "United States", status: "Inactive" },
  { name: "Bessie Cooper", company: "Qualcomm", phone: "(219) 555-0190", email: "bessie@qualcomm.com", country: "India", status: "Active" },
  { name: "Esther Howard", company: "PayPal", phone: "(702) 555-0122", email: "esther@paypal.com", country: "Luxembourg", status: "Active" },
  { name: "Darlene Robertson", company: "Square", phone: "(603) 555-0123", email: "darlene@square.com", country: "Canada", status: "Inactive" },
  { name: "Arthur Bradley", company: "Uber", phone: "(410) 555-0124", email: "arthur@uber.com", country: "Netherlands", status: "Active" },
  { name: "Mildred Kim", company: "Lyft", phone: "(530) 555-0125", email: "mildred@lyft.com", country: "United States", status: "Active" },
  { name: "Philip Carter", company: "DoorDash", phone: "(650) 555-0126", email: "philip@doordash.com", country: "Australia", status: "Inactive" },
  { name: "Lori Ferguson", company: "Instacart", phone: "(770) 555-0127", email: "lori@instacart.com", country: "Canada", status: "Active" },
  { name: "Samuel Gray", company: "Robinhood", phone: "(890) 555-0128", email: "samuel@robinhood.com", country: "United States", status: "Active" },
  { name: "Gloria Morales", company: "Coinbase", phone: "(910) 555-0129", email: "gloria@coinbase.com", country: "Ireland", status: "Active" },
  { name: "Dennis Hayes", company: "Binance", phone: "(930) 555-0130", email: "dennis@binance.com", country: "Malta", status: "Inactive" },
  { name: "Tiffany Hunt", company: "OpenAI", phone: "(950) 555-0131", email: "tiffany@openai.com", country: "United States", status: "Active" },
  { name: "Eugene Gardner", company: "Anthropic", phone: "(970) 555-0132", email: "eugene@anthropic.com", country: "United States", status: "Active" },
  { name: "Christina Reid", company: "DeepMind", phone: "(990) 555-0133", email: "christina@deepmind.com", country: "United Kingdom", status: "Active" },
  { name: "Lawrence Griffin", company: "Palantir", phone: "(110) 555-0134", email: "lawrence@palantir.com", country: "United States", status: "Inactive" },
  { name: "Paula Bryant", company: "Snowflake", phone: "(130) 555-0135", email: "paula@snowflake.com", country: "United States", status: "Active" },
  { name: "Sean Torres", company: "Databricks", phone: "(150) 555-0136", email: "sean@databricks.com", country: "United States", status: "Active" },
  { name: "Judith Rivera", company: "MongoDB", phone: "(170) 555-0137", email: "judith@mongodb.com", country: "Ireland", status: "Inactive" },
  { name: "Keith Peterson", company: "Redis", phone: "(190) 555-0138", email: "keith@redis.com", country: "Israel", status: "Active" },
  { name: "Amy Simmons", company: "Elastic", phone: "(210) 555-0139", email: "amy@elastic.com", country: "Netherlands", status: "Active" },
  { name: "Bryan Cox", company: "Cloudflare", phone: "(230) 555-0140", email: "bryan@cloudflare.com", country: "United States", status: "Active" },
  { name: "Angela Ward", company: "Vercel", phone: "(250) 555-0141", email: "angela@vercel.com", country: "United States", status: "Inactive" },
  { name: "Patrick Sanders", company: "Netlify", phone: "(270) 555-0142", email: "patrick@netlify.com", country: "United States", status: "Active" },
  { name: "Melissa Price", company: "Figma", phone: "(290) 555-0143", email: "melissa@figma.com", country: "United States", status: "Active" },
  { name: "Nathan Mitchell", company: "Linear", phone: "(310) 555-0144", email: "nathan@linear.com", country: "United States", status: "Active" },
  { name: "Hannah Scott", company: "Notion", phone: "(330) 555-0145", email: "hannah@notion.com", country: "United States", status: "Active" },
  { name: "Joshua Bell", company: "Airtable", phone: "(350) 555-0146", email: "joshua@airtable.com", country: "United States", status: "Inactive" },
  { name: "Sophia Adams", company: "Webflow", phone: "(370) 555-0147", email: "sophia@webflow.com", country: "United States", status: "Active" },
  { name: "Ethan Nelson", company: "Framer", phone: "(390) 555-0148", email: "ethan@framer.com", country: "Netherlands", status: "Active" },
  { name: "Olivia Carter", company: "Loom", phone: "(410) 555-0149", email: "olivia@loom.com", country: "United States", status: "Active" },
  { name: "Mason Mitchell", company: "Miro", phone: "(430) 555-0150", email: "mason@miro.com", country: "Russia", status: "Inactive" },
  { name: "Isabella Roberts", company: "Canva", phone: "(450) 555-0151", email: "isabella@canva.com", country: "Australia", status: "Active" },
  { name: "William Turner", company: "Intercom", phone: "(470) 555-0152", email: "william@intercom.com", country: "Ireland", status: "Active" },
  { name: "Ava Phillips", company: "Zendesk", phone: "(490) 555-0153", email: "ava@zendesk.com", country: "Denmark", status: "Inactive" },
  { name: "James Campbell", company: "Freshdesk", phone: "(510) 555-0154", email: "james@freshdesk.com", country: "India", status: "Active" },
  { name: "Charlotte Parker", company: "HubSpot", phone: "(530) 555-0155", email: "charlotte@hubspot.com", country: "United States", status: "Active" },
  { name: "Benjamin Evans", company: "Marketo", phone: "(550) 555-0156", email: "benjamin@marketo.com", country: "United States", status: "Active" },
  { name: "Mia Edwards", company: "Mailchimp", phone: "(570) 555-0157", email: "mia@mailchimp.com", country: "United States", status: "Inactive" },
  { name: "Lucas Collins", company: "SendGrid", phone: "(590) 555-0158", email: "lucas@sendgrid.com", country: "United States", status: "Active" },
  { name: "Amelia Stewart", company: "Twilio", phone: "(610) 555-0159", email: "amelia@twilio.com", country: "United States", status: "Active" },
  { name: "Henry Sanchez", company: "PagerDuty", phone: "(630) 555-0160", email: "henry@pagerduty.com", country: "Canada", status: "Inactive" },
  { name: "Harper Morris", company: "Datadog", phone: "(650) 555-0161", email: "harper@datadog.com", country: "France", status: "Active" },
  { name: "Alexander Rogers", company: "New Relic", phone: "(670) 555-0162", email: "alexander@newrelic.com", country: "United States", status: "Active" },
  { name: "Evelyn Reed", company: "Splunk", phone: "(690) 555-0163", email: "evelyn@splunk.com", country: "United States", status: "Active" },
  { name: "Daniel Cook", company: "Grafana", phone: "(710) 555-0164", email: "daniel@grafana.com", country: "Sweden", status: "Inactive" },
  { name: "Abigail Morgan", company: "Prometheus", phone: "(730) 555-0165", email: "abigail@prometheus.com", country: "Germany", status: "Active" },
  { name: "Michael Bailey", company: "Sentry", phone: "(750) 555-0166", email: "michael@sentry.com", country: "United States", status: "Active" },
  { name: "Emily Rivera", company: "LogRocket", phone: "(770) 555-0167", email: "emily@logrocket.com", country: "United States", status: "Inactive" },
  { name: "Matthew Cooper", company: "FullStory", phone: "(790) 555-0168", email: "matthew@fullstory.com", country: "United States", status: "Active" },
  { name: "Elizabeth Richardson", company: "Hotjar", phone: "(810) 555-0169", email: "elizabeth@hotjar.com", country: "Malta", status: "Active" },
  { name: "Jackson Cox", company: "Mixpanel", phone: "(830) 555-0170", email: "jackson@mixpanel.com", country: "United States", status: "Active" },
  { name: "Sofia Howard", company: "Amplitude", phone: "(850) 555-0171", email: "sofia@amplitude.com", country: "United States", status: "Inactive" },
  { name: "Aiden Ward", company: "Segment", phone: "(870) 555-0172", email: "aiden@segment.com", country: "United States", status: "Active" },
  { name: "Scarlett Torres", company: "mParticle", phone: "(890) 555-0173", email: "scarlett@mparticle.com", country: "United States", status: "Active" },
  { name: "Carter Peterson", company: "Braze", phone: "(910) 555-0174", email: "carter@braze.com", country: "United States", status: "Active" },
  { name: "Victoria Gray", company: "Iterable", phone: "(930) 555-0175", email: "victoria@iterable.com", country: "United States", status: "Inactive" },
  { name: "Owen Ramirez", company: "Klaviyo", phone: "(950) 555-0176", email: "owen@klaviyo.com", country: "United States", status: "Active" },
  { name: "Grace James", company: "ActiveCampaign", phone: "(970) 555-0177", email: "grace@activecampaign.com", country: "United States", status: "Active" },
  { name: "Wyatt Watson", company: "ConvertKit", phone: "(990) 555-0178", email: "wyatt@convertkit.com", country: "United States", status: "Inactive" },
  { name: "Chloe Brooks", company: "Drip", phone: "(112) 555-0179", email: "chloe@drip.com", country: "United States", status: "Active" },
  { name: "Jack Kelly", company: "Constant Contact", phone: "(132) 555-0180", email: "jack@constantcontact.com", country: "United States", status: "Active" },
  { name: "Lily Sanders", company: "Campaign Monitor", phone: "(152) 555-0181", email: "lily@campaignmonitor.com", country: "Australia", status: "Active" },
  { name: "Ryan Price", company: "GetResponse", phone: "(172) 555-0182", email: "ryan@getresponse.com", country: "Poland", status: "Inactive" },
  { name: "Zoey Bennett", company: "AWeber", phone: "(192) 555-0183", email: "zoey@aweber.com", country: "United States", status: "Active" },
  { name: "Nathan Wood", company: "Moosend", phone: "(212) 555-0184", email: "nathan@moosend.com", country: "Greece", status: "Active" },
  { name: "Penelope Barnes", company: "Omnisend", phone: "(232) 555-0185", email: "penelope@omnisend.com", country: "Estonia", status: "Inactive" },
  { name: "Leo Ross", company: "Sendlane", phone: "(252) 555-0186", email: "leo@sendlane.com", country: "United States", status: "Active" },
  { name: "Nora Henderson", company: "Postmark", phone: "(272) 555-0187", email: "nora@postmark.com", country: "United States", status: "Active" },
  { name: "Elijah Coleman", company: "SparkPost", phone: "(292) 555-0188", email: "elijah@sparkpost.com", country: "United States", status: "Active" },
  { name: "Hannah Jenkins", company: "Mandrill", phone: "(312) 555-0189", email: "hannah@mandrill.com", country: "United States", status: "Inactive" },
  { name: "Liam Perry", company: "Mailgun", phone: "(332) 555-0190", email: "liam@mailgun.com", country: "United States", status: "Active" },
  { name: "Aria Powell", company: "Amazon SES", phone: "(352) 555-0191", email: "aria@amazonses.com", country: "United States", status: "Active" },
  { name: "Grayson Long", company: "Brevo", phone: "(372) 555-0192", email: "grayson@brevo.com", country: "France", status: "Inactive" },
  { name: "Luna Patterson", company: "Resend", phone: "(392) 555-0193", email: "luna@resend.com", country: "United States", status: "Active" },
  { name: "Caleb Hughes", company: "Loops", phone: "(412) 555-0194", email: "caleb@loops.com", country: "United States", status: "Active" },
  { name: "Riley Flores", company: "Customer.io", phone: "(432) 555-0195", email: "riley@customer.io", country: "United States", status: "Active" },
  { name: "Hazel Washington", company: "Vero", phone: "(452) 555-0196", email: "hazel@vero.com", country: "Australia", status: "Inactive" },
  { name: "Isaiah Butler", company: "Autopilot", phone: "(472) 555-0197", email: "isaiah@autopilot.com", country: "Australia", status: "Active" },
  { name: "Violet Simmons", company: "Ortto", phone: "(492) 555-0198", email: "violet@ortto.com", country: "Australia", status: "Active" },
  { name: "Eli Foster", company: "Encharge", phone: "(512) 555-0199", email: "eli@encharge.com", country: "Bulgaria", status: "Inactive" },
  { name: "Stella Gonzalez", company: "UserEngage", phone: "(532) 555-0200", email: "stella@userengage.com", country: "Poland", status: "Active" },
  { name: "Levi Bryant", company: "Userlist", phone: "(552) 555-0201", email: "levi@userlist.com", country: "United States", status: "Active" },
  { name: "Aurora Alexander", company: "Custify", phone: "(572) 555-0202", email: "aurora@custify.com", country: "Romania", status: "Active" },
  { name: "Josiah Russell", company: "ChurnZero", phone: "(592) 555-0203", email: "josiah@churnzero.com", country: "United States", status: "Inactive" },
  { name: "Savannah Griffin", company: "Gainsight", phone: "(612) 555-0204", email: "savannah2@gainsight.com", country: "United States", status: "Active" },
  { name: "Mateo Diaz", company: "Totango", phone: "(632) 555-0205", email: "mateo@totango.com", country: "United States", status: "Active" },
  { name: "Layla Hayes", company: "Planhat", phone: "(652) 555-0206", email: "layla@planhat.com", country: "Sweden", status: "Inactive" },
  { name: "Julian Myers", company: "Vitally", phone: "(672) 555-0207", email: "julian@vitally.com", country: "United States", status: "Active" },
  { name: "Genesis Ford", company: "Catalyst", phone: "(692) 555-0208", email: "genesis@catalyst.com", country: "United States", status: "Active" },
  { name: "Ezra Hamilton", company: "Pendo", phone: "(712) 555-0209", email: "ezra@pendo.com", country: "United States", status: "Active" },
  { name: "Naomi Graham", company: "Appcues", phone: "(732) 555-0210", email: "naomi@appcues.com", country: "United States", status: "Inactive" },
  { name: "Micah Sullivan", company: "Chameleon", phone: "(752) 555-0211", email: "micah@chameleon.com", country: "United Kingdom", status: "Active" },
  { name: "Serenity Wallace", company: "Userflow", phone: "(772) 555-0212", email: "serenity@userflow.com", country: "Denmark", status: "Active" },
  { name: "Brayden West", company: "Userpilot", phone: "(792) 555-0213", email: "brayden@userpilot.com", country: "United Kingdom", status: "Inactive" },
  { name: "Aaliyah Cole", company: "Productboard", phone: "(812) 555-0214", email: "aaliyah@productboard.com", country: "Czech Republic", status: "Active" },
  { name: "Landon Bates", company: "Aha!", phone: "(832) 555-0215", email: "landon@aha.com", country: "United States", status: "Active" },
  { name: "Gabriella Chambers", company: "Roadmunk", phone: "(852) 555-0216", email: "gabriella@roadmunk.com", country: "Canada", status: "Active" },
  { name: "Angel Reyes", company: "Craft.io", phone: "(872) 555-0217", email: "angel@craft.io", country: "Israel", status: "Inactive" },
  { name: "Jaxon Houston", company: "Airfocus", phone: "(892) 555-0218", email: "jaxon@airfocus.com", country: "Germany", status: "Active" },
  { name: "Paisley Mendez", company: "Coda", phone: "(912) 555-0219", email: "paisley@coda.com", country: "United States", status: "Active" },
  { name: "Lincoln Cheng", company: "ClickUp", phone: "(932) 555-0220", email: "lincoln@clickup.com", country: "United States", status: "Inactive" },
  { name: "Elena Larson", company: "Asana", phone: "(952) 555-0221", email: "elena@asana.com", country: "United States", status: "Active" },
  { name: "Sawyer Castro", company: "Monday.com", phone: "(972) 555-0222", email: "sawyer@monday.com", country: "Israel", status: "Active" },
  { name: "Mackenzie Ortiz", company: "Basecamp", phone: "(992) 555-0223", email: "mackenzie@basecamp.com", country: "United States", status: "Active" },
  { name: "Kayden Gutierrez", company: "Trello", phone: "(113) 555-0224", email: "kayden@trello.com", country: "United States", status: "Inactive" },
  { name: "Piper Alvarez", company: "Jira", phone: "(133) 555-0225", email: "piper@jira.com", country: "Australia", status: "Active" },
  { name: "Colton Mendoza", company: "Confluence", phone: "(153) 555-0226", email: "colton@confluence.com", country: "Australia", status: "Active" },
  { name: "Sadie Romero", company: "Notion", phone: "(173) 555-0227", email: "sadie@notion2.com", country: "United States", status: "Inactive" },
  { name: "Bentley Aguilar", company: "Obsidian", phone: "(193) 555-0228", email: "bentley@obsidian.com", country: "United States", status: "Active" },
  { name: "Willow Perez", company: "Roam Research", phone: "(213) 555-0229", email: "willow@roamresearch.com", country: "United States", status: "Active" },
  { name: "Ryker Turner", company: "LogSeq", phone: "(233) 555-0230", email: "ryker@logseq.com", country: "China", status: "Active" },
  { name: "Kylie Phillips", company: "Capacities", phone: "(253) 555-0231", email: "kylie@capacities.io", country: "Germany", status: "Inactive" },
  { name: "Easton Campbell", company: "Mem", phone: "(273) 555-0232", email: "easton@mem.ai", country: "United States", status: "Active" },
  { name: "Clara Parker", company: "Reflect", phone: "(293) 555-0233", email: "clara@reflect.app", country: "United States", status: "Active" },
  { name: "Roman Evans", company: "Supernotes", phone: "(313) 555-0234", email: "roman@supernotes.app", country: "United Kingdom", status: "Inactive" },
  { name: "Jade Edwards", company: "Anytype", phone: "(333) 555-0235", email: "jade@anytype.io", country: "Germany", status: "Active" },
  { name: "Declan Collins", company: "AppFlowy", phone: "(353) 555-0236", email: "declan@appflowy.io", country: "United States", status: "Active" },
  { name: "Sienna Stewart", company: "Affine", phone: "(373) 555-0237", email: "sienna@affine.pro", country: "China", status: "Active" },
  { name: "Jace Sanchez", company: "Slab", phone: "(393) 555-0238", email: "jace@slab.com", country: "United States", status: "Inactive" },
  { name: "Adaline Morris", company: "Tettra", phone: "(413) 555-0239", email: "adaline@tettra.com", country: "United States", status: "Active" },
  { name: "Ryder Rogers", company: "Guru", phone: "(433) 555-0240", email: "ryder@guru.com", country: "United States", status: "Active" },
  { name: "Magnolia Reed", company: "Helpjuice", phone: "(453) 555-0241", email: "magnolia@helpjuice.com", country: "United States", status: "Inactive" },
  { name: "Zayden Cook", company: "Document360", phone: "(473) 555-0242", email: "zayden@document360.com", country: "United Kingdom", status: "Active" },
  { name: "Rosalie Morgan", company: "Archbee", phone: "(493) 555-0243", email: "rosalie@archbee.com", country: "Romania", status: "Active" },
  { name: "Knox Bailey", company: "GitBook", phone: "(513) 555-0244", email: "knox@gitbook.com", country: "France", status: "Active" },
  { name: "Cecilia Bell", company: "Docusaurus", phone: "(533) 555-0245", email: "cecilia@docusaurus.io", country: "United States", status: "Inactive" },
  { name: "Tobias Murphy", company: "ReadMe", phone: "(553) 555-0246", email: "tobias@readme.com", country: "United States", status: "Active" },
  { name: "Ophelia Bailey", company: "Stoplight", phone: "(573) 555-0247", email: "ophelia@stoplight.io", country: "United States", status: "Active" },
  { name: "Finnegan Rivera", company: "Redocly", phone: "(593) 555-0248", email: "finnegan@redocly.com", country: "Ukraine", status: "Inactive" },
  { name: "Meadow Cooper", company: "Swagger", phone: "(613) 555-0249", email: "meadow@swagger.io", country: "United States", status: "Active" },
  { name: "Sterling Richardson", company: "Postman", phone: "(633) 555-0250", email: "sterling@postman.com", country: "United States", status: "Active" },
  { name: "Josephine Cox", company: "Insomnia", phone: "(653) 555-0251", email: "josephine@insomnia.rest", country: "United States", status: "Active" },
  { name: "Caspian Howard", company: "Bruno", phone: "(673) 555-0252", email: "caspian@bruno.io", country: "India", status: "Inactive" },
  { name: "Clementine Ward", company: "Hoppscotch", phone: "(693) 555-0253", email: "clementine@hoppscotch.io", country: "India", status: "Active" },
  { name: "Rafferty Torres", company: "Thunder Client", phone: "(713) 555-0254", email: "rafferty@thunderclient.com", country: "Ireland", status: "Active" },
  { name: "Juniper Peterson", company: "HTTPie", phone: "(733) 555-0255", email: "juniper@httpie.io", country: "Czech Republic", status: "Inactive" },
  { name: "Stellan Gray", company: "Paw", phone: "(753) 555-0256", email: "stellan@paw.cloud", country: "France", status: "Active" },
  { name: "Cosima Ramirez", company: "RapidAPI", phone: "(773) 555-0257", email: "cosima@rapidapi.com", country: "United States", status: "Active" },
  { name: "Thaddeus James", company: "Kong", phone: "(793) 555-0258", email: "thaddeus@konghq.com", country: "United States", status: "Active" },
  { name: "Araminta Watson", company: "Tyk", phone: "(813) 555-0259", email: "araminta@tyk.io", country: "United Kingdom", status: "Inactive" },
  { name: "Peregrine Brooks", company: "Apigee", phone: "(833) 555-0260", email: "peregrine@apigee.com", country: "United States", status: "Active" },
  { name: "Isadora Kelly", company: "MuleSoft", phone: "(853) 555-0261", email: "isadora@mulesoft.com", country: "United States", status: "Active" },
  { name: "Leander Sanders", company: "WSO2", phone: "(873) 555-0262", email: "leander@wso2.com", country: "Sri Lanka", status: "Inactive" },
  { name: "Corinthia Price", company: "Boomi", phone: "(893) 555-0263", email: "corinthia@boomi.com", country: "United States", status: "Active" },
  { name: "Barnaby Bennett", company: "Informatica", phone: "(913) 555-0264", email: "barnaby@informatica.com", country: "United States", status: "Active" },
  { name: "Eulalia Wood", company: "Talend", phone: "(933) 555-0265", email: "eulalia@talend.com", country: "France", status: "Active" },
  { name: "Petunia Barnes", company: "Fivetran", phone: "(953) 555-0266", email: "petunia@fivetran.com", country: "United States", status: "Inactive" },
  { name: "Cornelius Ross", company: "Airbyte", phone: "(973) 555-0267", email: "cornelius@airbyte.com", country: "United States", status: "Active" },
  { name: "Aramis Henderson", company: "Stitch", phone: "(993) 555-0268", email: "aramis@stitchdata.com", country: "United States", status: "Active" },
  { name: "Seraphina Coleman", company: "dbt Labs", phone: "(114) 555-0269", email: "seraphina@getdbt.com", country: "United States", status: "Inactive" },
  { name: "Crispin Jenkins", company: "Lightdash", phone: "(134) 555-0270", email: "crispin@lightdash.com", country: "United Kingdom", status: "Active" },
  { name: "Allegra Perry", company: "Metabase", phone: "(154) 555-0271", email: "allegra@metabase.com", country: "United States", status: "Active" },
  { name: "Florentine Powell", company: "Superset", phone: "(174) 555-0272", email: "florentine@superset.io", country: "United States", status: "Active" },
  { name: "Leontine Long", company: "Redash", phone: "(194) 555-0273", email: "leontine@redash.io", country: "Israel", status: "Inactive" },
  { name: "Sylvester Hughes", company: "Grafana", phone: "(214) 555-0274", email: "sylvester@grafana2.com", country: "Sweden", status: "Active" },
  { name: "Celestine Flores", company: "Tableau", phone: "(234) 555-0275", email: "celestine@tableau.com", country: "United States", status: "Active" },
  { name: "Ignatius Washington", company: "Power BI", phone: "(254) 555-0276", email: "ignatius@powerbi.com", country: "United States", status: "Inactive" },
  { name: "Araminta Butler", company: "Looker", phone: "(274) 555-0277", email: "araminta2@looker.com", country: "United States", status: "Active" },
  { name: "Ptolemy Simmons", company: "Sisense", phone: "(294) 555-0278", email: "ptolemy@sisense.com", country: "Israel", status: "Active" },
];

async function main() {
  await db.customer.createMany({
    data: customers,
    skipDuplicates: true,
  });
  console.log(`Seeded ${customers.length} customers`);
}

main()
  .catch(console.error)
  .finally(() => db.$disconnect());